version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ebay-optimizer-backend
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME=eBay Listing Optimizer
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://localhost:80,http://localhost
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_URL=sqlite:///./ebay_optimizer.db
    volumes:
      - ./backend/ebay_optimizer.db:/app/ebay_optimizer.db
      - ./credentials:/app/credentials:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ebay-optimizer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: ebay-optimizer-network