version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ebay-optimizer-backend-prod
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME=eBay Listing Optimizer
      - BACKEND_CORS_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=sqlite:///./ebay_optimizer.db
      - GOOGLE_SHEETS_CREDENTIALS_PATH=credentials/google-service-account.json
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_API_URL=https://yourdomain.com/api/v1
    container_name: ebay-optimizer-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Reverse proxy for SSL
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./ssl:/etc/nginx/certs:ro
    restart: unless-stopped
    profiles:
      - ssl

networks:
  default:
    name: ebay-optimizer-prod-network

volumes:
  data:
  logs: